# Generated by Django 5.2.16 on 2026-07-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Books', 'Books'), ('Home', 'Home'), ('Sports', 'Sports'), ('Beauty', 'Beauty')], max_length=100, null=True),
        ),
    ]
